USE QLBongDa
--   SELECT * FROM BANGXH
--   SELECT * FROM CAULACBO
--   SELECT * FROM CAUTHU
--   SELECT * FROM HLV_CLB
--   SELECT * FROM HUANLUYENVIEN
--   SELECT * FROM QUOCGIA
--   SELECT * FROM SANVD
--   SELECT * FROM TINH
--   SELECT * FROM TRANDAU

